version: '3'

services:
  keycloak:
    # image: quay.io/keycloak/keycloak:25.0.4
    image: kc-falco
    container_name: keycloak
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${PWD}/hack/test-realm.json
        target: /opt/keycloak/data/import/realm.json
        read_only: true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      FALCO_ENDPOINT: http://falco:7080/keycloak
      FALCO_ADMIN_EVENTS: "true"
    command:
      - start-dev
      - --import-realm
      - --log-level="INFO,com.github.mattiaforc.keycloak:TRACE"
    ports:
      - "8080:8080"

  falco:
    image: falcosecurity/falco:latest
    container_name: falco
    privileged: true
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - /etc:/host/etc:ro
      - ${PWD}/hack/falco.yaml:/etc/falco/falco.yaml
      - ${PWD}/hack/keycloak_rules.yaml:/etc/falco/keycloak_rules.yaml
      - type: bind
        read_only: true
        source: ${PWD}/hack/libkeycloak.so
        target: /usr/share/falco/plugins/libkeycloak.so
    ports:
      - "7080:7080"

  falco-sidekick:
    depends_on: [ falco ]
    image: falcosecurity/falcosidekick:latest
    container_name: falco-sidekick
    environment:
      - WEBUI_URL=http://falcosidekick-ui:2802
    volumes:
      - ${PWD}/hack/sidekick.yaml:/etc/falco/falcosidekick.yaml

  falcosidekick-ui:
    depends_on: [ falco-sidekick, redis ]
    image: falcosecurity/falcosidekick-ui:latest
    container_name: falcosidekick-ui
    environment:
      - FALCOSIDEKICK_UI_REDIS_URL=redis:6379
    ports:
      - "2802:2802"

  redis:
    image: redis/redis-stack:latest
    container_name: redis

  echo-server:
    image: ealen/echo-server
    container_name: echo-server
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
      PORT: 7080
      LOG_HTTP_BODY: "true"
      LOG_HTTP_HEADERS: "true"
    profiles:
      - extra